github.com:
    users:
        pityumajsaii-cell:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: pityumajsaii-cell
